require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Style/FrozenStringLiteralComment:
  Exclude:
    - Guardfile
    - spec/**/*_spec.rb

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 50

RSpec/MultipleMemoizedHelpers:
  Enabled: false
