require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 160

Style/FrozenStringLiteralComment:
  Exclude:
    - Guardfile
    - spec/**/*_spec.rb

Metrics/CyclomaticComplexity:
  Max: 15
  Exclude:
    - spec/**/*_spec.rb
    - lib/icarus/mod/cli/*.rb # Thor command files

Metrics/PerceivedComplexity:
  Max: 15
  Exclude:
    - spec/**/*_spec.rb
    - lib/icarus/mod/cli/*.rb # Thor command files

Metrics/AbcSize:
  Max: 25
  Exclude:
    - lib/icarus/mod/cli/*.rb # Thor command files

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Documentation:
  Exclude:
    - lib/icarus/mod/cli/*.rb # Thor command files

Style/OpenStructUse:
  Enabled: false
